apiVersion: v1
kind: Service
metadata:
  name: langchain-gemini-service
spec:
  selector:
    app: langchain-gemini-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
