apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgvector
  labels:
    app: pgvector
spec:
  serviceName: pgvector
  replicas: 2
  selector:
    matchLabels:
      app: pgvector
  template:
    metadata:
      labels:
        app: pgvector
    spec:
      containers:
        - name: postgres
          image: postgres:15
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: adminpassword
            - name: POSTGRES_DB
              value: pgvector_db
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - |
                    psql -U admin -d pgvector_db -c "CREATE EXTENSION IF NOT EXISTS vector;"
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgvector-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pgvector
  labels:
    app: pgvector
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    app: pgvector
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgvector-pvc
  labels:
    app: pgvector
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi